changelog:
  exclude:
    labels:
      - Release
  categories:
    - title: 🚀 Features
      labels:
        - Feature
    - title: 🐛 Bug Fixes
      labels:
        - Bug
    - title: Other Changes
      labels:
        - "*"